services:
  postgres:
    image: postgres:17-alpine
    container_name: red_social_db
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - net_red_social
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}  

volumes:
  pgdata:

networks:
  net_red_social:
    driver: bridge